In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('spam_processed.csv')

In [5]:
df.head()

target                                               text  num_char  \
0       0  Go until jurong point, crazy.. Available only ...       111   
1       0                      Ok lar... Joking wif u oni...        29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...       155   
3       0  U dun say so early hor... U c already then say...        49   
4       0  Nah I don't think he goes to usf, he lives aro...        61   

   num_words  num_sen                                     processed_text  
0         24        2  go jurong point crazi avail bugi n great world...  
1          8        2                              ok lar joke wif u oni  
2         37        2  free entri 2 wkli comp win fa cup final tkt 21...  
3         13        1                u dun say earli hor u c alreadi say  
4         15        1          nah dont think goe usf live around though

In [7]:
%pip install scikit-learn

from sklearn.feature_extraction.text import CountVectorizer 


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/10.7 MB 3.6 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/10.7 MB 3.2 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/10.7 MB 3.9 MB/s eta 0:00:03
   ------------- -------------------------- 3.7/10.7 MB 4.3 MB/s eta 0:00:02
   ----------------- ---------------------- 4.7/10.7 MB 4.6 MB/s eta 0:00:02
   --------------------- ------------------ 5.8/10.7 MB 4.7 MB/s eta 0:00:02
   -------------------------- ------------- 7.1/10.7 MB 4.9 MB/s eta 0:00:01
   ------------------------------ --------- 8.1/10.7 MB 5.1 MB/s eta 0:00:01
   ----------------------------------- ---- 9.4/10.7 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------  10.5/10.7 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  10.5/10.7 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------- 10.7/10.7 MB 4.4 MB/s eta 0:00:00
   

In [8]:
cv= CountVectorizer()

In [10]:
x = cv.fit_transform(df['processed_text'].fillna("")).toarray()

In [11]:
y=df['target'].values

In [12]:
y

array([0, 0, 1, ..., 0, 0, 0], shape=(5169,))

In [13]:
from sklearn.model_selection import train_test_split    

In [14]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [15]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB  
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [17]:
nb= MultinomialNB()
gb= GaussianNB()
bnb= BernoulliNB()

In [20]:
from sklearn.metrics import precision_score

gb.fit(X_train, y_train)
y_pred = gb.predict(X_test)
print("Gaussian Naive Bayes Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print(precision_score(y_test, y_pred, average='weighted'))

Gaussian Naive Bayes Accuracy: 0.8723404255319149
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.87      0.92       889
           1       0.53      0.88      0.66       145

    accuracy                           0.87      1034
   macro avg       0.75      0.87      0.79      1034
weighted avg       0.91      0.87      0.88      1034

Confusion Matrix:
 [[775 114]
 [ 18 127]]
0.9141506011092245


In [21]:
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)
print("Gaussian Naive Bayes Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print(precision_score(y_test, y_pred, average='weighted'))

Gaussian Naive Bayes Accuracy: 0.9748549323017408
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.99       889
           1       0.90      0.92      0.91       145

    accuracy                           0.97      1034
   macro avg       0.95      0.95      0.95      1034
weighted avg       0.98      0.97      0.97      1034

Confusion Matrix:
 [[875  14]
 [ 12 133]]
0.9750129774596661


In [22]:
bnb.fit(X_train, y_train)
y_pred = bnb.predict(X_test)
print("Gaussian Naive Bayes Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print(precision_score(y_test, y_pred, average='weighted'))

Gaussian Naive Bayes Accuracy: 0.9690522243713733
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98       889
           1       0.97      0.80      0.88       145

    accuracy                           0.97      1034
   macro avg       0.97      0.90      0.93      1034
weighted avg       0.97      0.97      0.97      1034

Confusion Matrix:
 [[886   3]
 [ 29 116]]
0.9692152626024885


In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.metrics import precision_score

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "SVC": SVC(),
    "LinearSVC": LinearSVC(max_iter=10000),
    "KNN": KNeighborsClassifier(),
    "MultinomialNB": MultinomialNB(),
    "GaussianNB": GaussianNB(),
    "BernoulliNB": BernoulliNB()
}

results = {}

for name, model in models.items():
    # GaussianNB needs dense input
    if name == "GaussianNB":
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
    precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    results[name] = precision

for name, precision in results.items():
    print(f"{name}: Precision = {precision:.4f}")

Logistic Regression: Precision = 0.9762
Decision Tree: Precision = 0.9513
Random Forest: Precision = 0.9680
Gradient Boosting: Precision = 0.9571
AdaBoost: Precision = 0.9060
SVC: Precision = 0.9707
LinearSVC: Precision = 0.9802
KNN: Precision = 0.9146
MultinomialNB: Precision = 0.9750
GaussianNB: Precision = 0.9142
BernoulliNB: Precision = 0.9692
